### ISSUE TITLE
0.1.11 fails to build on 32-bit architectures (e.g., armv7, i386, powerpc)

### ISSUE THREAD

**Issue by jbeich** [waycrate/xdg-desktop-portal-luminous#86]
Regressed by #81. From [error log](https://pkg-status.freebsd.org/beefy21/data/142i386-default/8b06c03ce600/logs/errors/xdg-desktop-portal-luminous-0.1.11.log):

```rust
$ cargo build --target i686-unknown-freebsd
[...]
error[E0283]: type annotations needed
   --> src/remotedesktop/state.rs:139:47
    |
139 |                 if state == KeyState::Pressed.into() {
    |                          --                   ^^^^
    |                          |
    |                          type must be known at this point
    |
    = note: multiple `impl`s satisfying `u32: PartialEq<_>` found in the following crates: `core`, `glib`:
            - impl PartialEq for u32;
            - impl PartialEq<glib::types::ULong> for u32;
help: try using a fully qualified path to specify the expected types
    |
139 -                 if state == KeyState::Pressed.into() {
139 +                 if state == <KeyState as Into<T>>::into(KeyState::Pressed) {
    |

error[E0283]: type annotations needed
   --> src/remotedesktop/state.rs:146:47
    |
146 |                 if state == KeyState::Pressed.into() {
    |                          --                   ^^^^
    |                          |
    |                          type must be known at this point
    |
    = note: multiple `impl`s satisfying `u32: PartialEq<_>` found in the following crates: `core`, `glib`:
            - impl PartialEq for u32;
            - impl PartialEq<glib::types::ULong> for u32;
help: try using a fully qualified path to specify the expected types
    |
146 -                 if state == KeyState::Pressed.into() {
146 +                 if state == <KeyState as Into<T>>::into(KeyState::Pressed) {
    |
```

**Comment by Decodetalkers** [comment]
can you see if this fix your problem?

https://github.com/waycrate/xdg-desktop-portal-luminous/pull/87

**Comment by Decodetalkers** [comment]
> I confirm, [#87](https://github.com/waycrate/xdg-desktop-portal-luminous/pull/87) does help unbreak build.

ok. I merge that branch, you can add a patch to the build
